version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: kvil_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend-api:
    image: baohp17/kvil-backend:v1
    container_name: kvil_backend_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      - PORT=8080
      - DB_HOST=mysql-db #
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=development
      - DB_DIALECT=mysql

volumes:
  mysql_data:
